### ISSUE TITLE
Doesn't do anything if already have match for root

### ISSUE THREAD

**Issue by SergeAstapov** [snewcomer/intersection-observer-admin#30]
@snewcomer looks like changes in #28 cause an issue:
when we observe two elements with different options but the same `root`, only first element is "watched".

I've setup [simple reproduction repo](https://github.com/SergeAstapov/io-admin-repro-28) where you can see the issue.

Here is [the commit](https://github.com/SergeAstapov/io-admin-repro-28/commit/caa5fd6f99b342c894c4ae1b9d0076d8deb120db) which adds the problematic code:
* we have two elements
* both elements share same `root` (root is implicitly `window`)
* two elements have different `rootMargin` via `viewportTolerance`
* only first element is watched, the second one is ignored.

Couldn't grasp what bug #28 fixes to create a PR hence would love to hear your @snewcomer thoughts on this.

**Comment by snewcomer** [comment]
https://github.com/DockYard/ember-in-viewport/pull/270

It was this PR.  

Hm.  That is bad. The original changes were to fix test failures due to an unknown cause - the options all of a sudden had state persisted on them that were also used in the IO callback.  This is after a long time of no changes to this file.  So likely browser/spec change.  I'll revert in any case to give myself more time to investigate.

https://github.com/snewcomer/intersection-observer-admin/blob/88b4c33a6eb930d26eeba91644d857c8277ef3af/src/index.ts#L179

https://github.com/snewcomer/intersection-observer-admin/blob/88b4c33a6eb930d26eeba91644d857c8277ef3af/src/index.ts#L197

**Comment by snewcomer** [comment]
https://github.com/DockYard/ember-in-viewport/pull/273/checks?check_run_id=2496407040

**Comment by SergeAstapov** [comment]
Thank you @snewcomer for quick response! I've tested intersection-observer-admin@0.3.2 via ember-in-viewport@3.10.2 and it works like a charm!
